name: Build C++

on:
        push:
                branches: [main, other]
        pull request:
                branches: [main, other]

jobs:
        install:
                runs-on: ubuntu-latest

                steps:
                        name: Install dependencies
                        run:
                                sudo apt install g++

                build:
                        needs: install
                        runs-on: ubuntu-latest

                        steps:
                                uses:
                                name: Build project
                                run: 
                                        g++ main.cpp --std=c++17 -o Palette
                                        ./Palette 000 afC940 876 5104 FEFED 9964Ba 00G000
