name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: g++ main.cpp --std=c++17 -o Palette
    - name: test
      run: ./Palette 000 afC940 876 5104 FEFED 9964Ba 00G000
